.TH SGT-LAUNCHER "1" "September 2021" "sgt-launcher 0.2" "User Commands"
.SH NAME
sgt-launcher \- launcher for Simon Tatham's Portable Puzzle Collection
.SH SYNOPSIS
.B sgt-launcher
[\fI\,options\/\fR]
.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Show debug messages
.SH BUGS
Please report bugs at https://github.com/bluesabre/sgt-launcher/issues
.SH AUTHOR
Sean Davis (sean@bluesabre.org)
