#!/usr/bin/env python

import sys
import signal

from sgtlauncher.SgtLauncher import MyApplication

if __name__ == "__main__":
    # Allow application shutdown with Ctrl-C in terminal
    signal.signal(signal.SIGINT, signal.SIG_DFL)

    app = MyApplication()
    exit_status = app.run(sys.argv)
    sys.exit(exit_status)
